version: "3.9"

services:
  database:
    image: postgres
    container_name: toro
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=toro
      - POSTGRES_PASSWORD=toro
      - POSTGRES_DB=toro
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local